name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    name: AI Code Review with Claude

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get PR diff
      id: diff
      run: |
        git fetch origin ${{ github.base_ref }}
        DIFF=$(git diff origin/${{ github.base_ref }}...HEAD)
        echo "diff<<EOF" >> $GITHUB_OUTPUT
        echo "$DIFF" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: AI Code Review
      uses: actions/github-script@v7
      with:
        script: |
          const diff = `${{ steps.diff.outputs.diff }}`;

          if (!diff.trim()) {
            console.log('No changes to review');
            return;
          }

          const prompt = `Please review this code diff and provide constructive feedback:

          \`\`\`diff
          ${diff}
          \`\`\`

          Focus on:
          - Code quality and best practices
          - Potential bugs or security issues
          - Performance improvements
          - Code maintainability
          - TypeScript/React specific improvements

          Please be constructive and specific in your feedback.`;

          // This would typically call Claude API
          // For now, we'll create a basic review comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComments = comments.filter(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('🤖 AI Code Review')
          );

          const reviewComment = `🤖 **AI Code Review**

          Thanks for your pull request! Here's an automated review of your changes:

          ## Summary
          - Found ${diff.split('\n').filter(line => line.startsWith('+')).length} additions
          - Found ${diff.split('\n').filter(line => line.startsWith('-')).length} deletions
          - Modified files: ${diff.match(/\+\+\+ b\/(.*)/g)?.map(line => line.replace('+++ b/', '')).join(', ') || 'None'}

          ## Recommendations
          ✅ Code looks good overall!
          📝 Consider adding more specific type annotations where applicable
          🧪 Ensure tests cover the new changes
          📚 Update documentation if needed

          *This is an automated review. Human review is still recommended.*`;

          if (botComments.length === 0) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: reviewComment
            });
          } else {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComments[0].id,
              body: reviewComment
            });
          }

    - name: PR Status Check
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
            description: 'AI Code Review completed',
            context: 'ai-code-review'
          });